env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb
  - airbnb-typescript
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/prop-types: 0
  react/function-component-definition: 0
settings:
  react:
    version: detect
